tag_prefix = "v"
from_latest_tag = false
ignore_merge_commits = false
disable_changelog = false
generate_mono_repository_global_tag = true
branch_whitelist = []
skip_ci = "[skip ci]"
skip_untracked = false
pre_bump_hooks = [
  "cargo set-version {{version}}",
  "cargo readme -o README.md",
]
post_bump_hooks = [
  "git push",
  "git push origin {{version_tag}}",
  "cp target/release/ghsec ghsec-x86_64-unknonwn-linux-gnu",
  "cog changelog --at {{version_tag}} -t remote > GITHUB_CHANGELOG.md",
  "gh release create {{version_tag}} -F GITHUB_CHANGELOG.md ghsec-x86_64-unknonwn-linux-gnu"
]
pre_package_bump_hooks = []
post_package_bump_hooks = []

[git_hooks]

[commit_types]

[changelog]
path = "CHANGELOG.md"
template = "remote"
remote = "github.com"
repository = "ghsec"
owner = "vtavernier"
authors = [
  { username = "vtavernier", signature = "Vincent Tavernier" }
]

[bump_profiles]

[packages]
