name: main

on:
  push:
    branches:
      - master
    tags-ignore:
      - '**'

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      release: true
    permissions:
      contents: write
      actions: read
      pages: write
      id-token: write
